### ISSUE TITLE
Not working in Zebra b21 and newer

### ISSUE THREAD

**Issue by edmechem** [Samgisaninja/tweakcompatible-zebra#3]
TweakCompatible for Zebra has been working great up through (both versions of) Zebra b20-3, but is broken in Zebra b21 & b22.   TCfZ is getting "(null)" instead of the tweak ID (i.e. "com.wh0ba.storage3d").  See screenshots below.  Chatting w Wilson in Zebra Discord, he said nothing significant changed between b20 & b21.

**Comment by edmechem** [comment]
Screenshots of it working in b20 & earlier: https://imgur.com/a/wLaCDq1

**Comment by edmechem** [comment]
Screenshots of it broken in b21 & b22: https://imgur.com/a/omXcY1e

**Comment by edmechem** [comment]
![67E527C8-D8DD-4363-9B67-340FA5A385FA](https://user-images.githubusercontent.com/171138/64557393-4ef55700-d2f6-11e9-9f00-8c69d3842840.jpeg)
![1057133C-8FDC-4731-9617-F37EF5868BAA](https://user-images.githubusercontent.com/171138/64557394-4f8ded80-d2f6-11e9-9829-82257d6df1e3.jpeg)

**Comment by LouSkunt** [comment]
Can confirm. 
I’ve been having the exact same issue. I made a post asking about it on the r/jailbreak subreddit but never got any comments.
If you tap on view all reports it doesn’t load the right page either. There are never any entries, not even the tweak name either.

Would be awesome to have this functioning as tweakreviewDB isn’t a replacement but rather a complimenting tweak. Some tweaks are only reported on in one but not the other.

**Comment by Samgisaninja** [comment]
So this got fixed but now it's broken by b25 again

:rip:
