### ISSUE TITLE
Version 1.1.4 not working on iPhone X 

### ISSUE THREAD

**Issue by AppleMali90** [Samgisaninja/tweakcompatible-zebra#4]
When pressing the + button it crashes Zebra all the times

**Comment by Samgisaninja** [comment]
Works fine here: https://streamable.com/xmkob

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Samgisaninja** [comment]
What package are you trying to add a report to?

**Comment by AppleMali90** [comment]
Sorry It works... I didn’t update Zebra to the new version 😊
